### ISSUE TITLE
Elixir Podcast!

### ISSUE THREAD

**Issue by matsfan** [ElixirTalk/elixirtalk#14]
Guys,

I am at the very beginning of my Elixir journey and I am so happy there is a podcast. I'm listening to the first episode right now and I look forward to many more future episodes!

**Comment by desmondmonster** [comment]
thanks!  feel free to ask us anything.  After you've been working with a technology for a while you tend to gloss over the things that were confusing at first, but that's our own blind spot and those topics are no less valuable.  I'm sure others on the path would appreciate it.

And be sure to check out https://elixirforum.com/ for more discussion if you haven't already!
