### ISSUE TITLE
How much Erlang do I need/should I learn?

### ISSUE THREAD

**Issue by Sgoettschkes** [ElixirTalk/elixirtalk#19]
I recently switched jobs and am now developing a web application in Elixir and Phoenix. I have no prior knowledge of Erlang/Elixir or Ruby (and Ruby on Rails) other than some code examples/hello world tutorials. In the past, I have worked with languages like PHP and Python and have spent the last year working on a project in Clojure and Clojurescript.

In your opinion, how much time should I invest to learn Erlang/OTP/Beam compared to Elixir/Phoenix?

**Comment by desmondmonster** [comment]
https://soundcloud.com/elixirtalk/episode-108-managing-multiple-elixir-versions-how-much-erlang-should-you-know-and-thinking-functionally
