### ISSUE TITLE
How to "Mock/stub" in tests for external APIs for integration tests

### ISSUE THREAD

**Issue by fozcodes** [ElixirTalk/elixirtalk#20]
Mocking in elixir isn't typically done in the classical sense. I'm a big fan of Webmock in Ruby, or Nock in Node, but that's not the suggested route in Elixir.

We recently had to mock a 3rd party api and we used the method described here: http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/

It worked well because we could test simple cases with hard-coded pre-baked responses in our Mock module. And for unit tests when you're testing a module directly it's great.

But when we needed to have more dynamic responses on a per-test basis for integration (in our case Wallaby-based), we ended up turning our Mock into an Agent that you could preload with X records or results for a given request. 

I'm not sure if that's The Right Way™, or not. Seems to work, but is there some better approach? What are people doing out there in the wild?

**Comment by desmondmonster** [comment]
https://soundcloud.com/elixirtalk/episode-107-multiple-databases-mocking-external-tests
