### ISSUE TITLE
Authorization and Authentication in Phoenix projects

### ISSUE THREAD

**Issue by mariozig** [ElixirTalk/elixirtalk#23]
I'm a new listener so apologies if this is was covered (still listening to older episodes)

It sounds like both of you have experience with Phoenix and I'd love to hear how and what you guys are doing for both authentication and authorization.  It would be interesting to hear beyond just a drop in library name but more like experiences you've had, limitations, features, etc.

**Comment by desmondmonster** [comment]
https://soundcloud.com/elixirtalk/episode-109-authorization-authentication-in-phoenix-apps-higher-level-app-patterns

**Comment by mariozig** [comment]
Awesome episode. Thanks!
