### ISSUE TITLE
Thinking Functionally

### ISSUE THREAD

**Issue by mariozig** [ElixirTalk/elixirtalk#25]
if you guys have come from an oo background I'm interested to know how the transition went.  

Specifically stuff like: 

- What was hard?
- What do you miss?
- What is better?
- How others can do it?
- Elixir vs other functional languages 
- etc

**Comment by desmondmonster** [comment]
https://soundcloud.com/elixirtalk/episode-108-managing-multiple-elixir-versions-how-much-erlang-should-you-know-and-thinking-functionally
