### ISSUE TITLE
How to schedule code!

### ISSUE THREAD

**Issue by desmondmonster** [ElixirTalk/elixirtalk#3]
@googleiapple

**Comment by fozcodes** [comment]
I'll +1 this. I heard @desmondmonster mention that cron-esque email sending with processes that sleep for a week at a time. I'm interested in hearing more details. _Time is the fire in which we burn_... (yes, I just referenced _Generations_)

**Comment by desmondmonster** [comment]
@fozcodes thanks for the suggestion.  In the meantime, I gave a presentation at the NYC Elixir meetup a while back about something very similar for a todo app I built:  https://speakerdeck.com/desmondmonster/recurring-tasks-in-elixir

We're taking a holiday break but hopefully the slides give you some guidance!
