### ISSUE TITLE
How to best handle behavior implementations with shared functionality

### ISSUE THREAD

**Issue by eboswort** [ElixirTalk/elixirtalk#31]
**The main question**
The application I'm working on (originally written by Desmond) sends notifications via email and sms. The notifications are triggered by JSON messages received over AMQP. The codebase contains a bunch of "Processors" that each implement logic to get a message from AMQP and conditionally trigger an email and/or text message. Right now they are separate modules with no relation that share a lot of logic. *I'd like to DRY up the processor code and also add some structure to how processors work in the application. What are my options?*

**some more thoughts**
My instinct is that there should be a `Processor` behavior. A processor at it's most basic level just has a process function that accepts a json string and ends up maybe sending an email or text, but the processors share more logic than that. They could potentially share a `process` implementation like
```
def process(json_string) do
  json_string
  |> parse_json_to_map()
  |> parse_map_to_event_schema()
  |> send_email_if_email_should_be_sent()
  |> send_text_if_text_should_be_sent()
end
```
So I could make a Processor behavior that defines that function as well as a default value for each of these steps that could be overridden, but that sounds like a bad direction to me. Before long there will be a tangle of function calls in and out of the parent behavior and its implementations. And I think in order to override these methods I would have to make them public which is lame and seems like an indication that I'd be on the wrong path. Are there other patterns I should consider?

**Comment by mmmries** [comment]
One way that I've done this in the past is with a pattern that includes both behaviors and a plug-like pattern of assembling pipelines of functions https://gist.github.com/mmmries/424afa5b73ef597d56037b5b2591561e

**Comment by eboswort** [comment]
@mmmries Ooh yea I love the plug approach. I think that'll allow for much more granular pieces of shared functionality.
