### ISSUE TITLE
Add RSS feed playable in podcast players (like AnetnnaPod and so on)?

### ISSUE THREAD

**Issue by ivan-kolmychek** [ElixirTalk/elixirtalk#33]
The episode downloads are available (#30), but there is no RSS feed.

After quick googling it looks like [SoundCloud actually supports RSS, but it needs to be set up](https://creatorguide.soundcloud.com/podcasting)

It would be nice to have it.

**Comment by ivan-kolmychek** [comment]
On the second note, it looks like https://getrssfeed.com/ is able to find the feed.

Should this issue be closed?

**Comment by cjbell** [comment]
Closing as RSS feed is present
