### ISSUE TITLE
where can I find show notes?

### ISSUE THREAD

**Issue by Vaysman** [ElixirTalk/elixirtalk#38]
I've tried http://elixirtalk.com/ but got **502 Bad Gateway**

**Comment by secondspass** [comment]
Show notes are in the descriptions of the individual episodes on [Soundcloud](https://soundcloud.com/elixirtalk) and [iTunes](https://itunes.apple.com/us/podcast/elixirtalk/id1298287048)

**Comment by Vaysman** [comment]
thank you
