### ISSUE TITLE
Chris' PR management tool

### ISSUE THREAD

**Issue by hwood-sp** [ElixirTalk/elixirtalk#47]
Hi Chris,

I also struggle at work with good PR management. I would love to see your elixir/react/electron taskbar app when you open source it. Even if it's not fully ready, I'd be happy to take an early look and hopefully give feedback.

Love your show btw : )

~ Harlan

**Comment by hwood-sp** [comment]
@cjbell

**Comment by desmondmonster** [comment]
answered! https://soundcloud.com/elixirtalk/episode-143-community-questions-graphql
