### ISSUE TITLE
Add time code to podcast

### ISSUE THREAD

**Issue by vermaxik** [ElixirTalk/elixirtalk#53]
Hi guys,

First of all I would like to say thank you a lot for Elixir podcasts, it’s really enjoyable and useful 👍 

But sometimes I would like to jump to specific topic which described at description/links and it’ll make our life easy if you write time code next to topic/link.

Hope it’s not so hard to implement, but sure a lot of subscribers will happy if you make it 😉

Thank you in advance!

~Maksym

**Comment by cjbell** [comment]
Thanks @vermaxik - from episode 163 (the latest) I started adding timecodes to topics in the show notes. Will aim to keep that up! Thanks for your support 👍
