### ISSUE TITLE
When to use umbrella in elixir apps?

### ISSUE THREAD

**Issue by desmondmonster** [ElixirTalk/elixirtalk#7]
@apcxiii

**Comment by lamenyq** [comment]
also, how to structure them.  Would be nice to hear you guys elaborate on the acme_bank example.

https://github.com/wojtekmach/acme_bank

and 

https://medium.com/@andreichernykh/thoughts-on-structuring-an-elixir-phoenix-project-cb083a8894ef

**Comment by desmondmonster** [comment]
https://soundcloud.com/elixirtalk/episode-103-umbrella-apps
